-- 2️⃣ Create Iceberg Table and Populate Data
USE SCHEMA WS_QS_DB.iceberg_qs;

CREATE OR REPLACE ICEBERG TABLE ws_qs_dim_customer
(
    C_CUSTKEY STRING,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_NATIONKEY STRING,
    C_PHONE STRING,
    C_ACCTBAL STRING,
    C_MKTSEGMENT STRING,
    C_COMMENT STRING
)
EXTERNAL_VOLUME = 'WS_ExVol_IcebergQS'
CATALOG = snowflake
BASE_LOCATION = 'ws_qs_dim_customer';

INSERT INTO ws_qs_dim_customer
  SELECT TOP 500 * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

SELECT * FROM ws_qs_dim_customer LIMIT 10;
