-- Snowflake Demo Database for Fabric Mirroring Workshop

CREATE OR REPLACE DATABASE FABRIC_MIRROR_DEMO;
USE DATABASE FABRIC_MIRROR_DEMO;
CREATE OR REPLACE SCHEMA SALES;

-- Customers table
CREATE OR REPLACE TABLE SALES.CUSTOMERS (
    CUSTOMER_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_NAME STRING,
    COUNTRY STRING
);

-- Products table
CREATE OR REPLACE TABLE SALES.PRODUCTS (
    PRODUCT_ID INT AUTOINCREMENT PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

-- Orders table
CREATE OR REPLACE TABLE SALES.ORDERS (
    ORDER_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    ORDER_DATE DATE,
    STATUS STRING,
    TOTAL_AMOUNT NUMBER(10,2)
);

-- Sample data
INSERT INTO SALES.CUSTOMERS (CUSTOMER_NAME, COUNTRY) VALUES
('Alice Smith','US'),
('Bob Johnson','UK'),
('Carlos López','MX'),
('Diana Lee','CA'),
('Ethan Brown','DE');

INSERT INTO SALES.PRODUCTS (PRODUCT_NAME, CATEGORY, PRICE) VALUES
('Laptop','Electronics',1200.00),
('Phone','Electronics',850.00),
('Desk','Furniture',300.00),
('Chair','Furniture',150.00),
('Headphones','Accessories',100.00);

INSERT INTO SALES.ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, ORDER_DATE, STATUS, TOTAL_AMOUNT) VALUES
(1, 1, 1, '2025-01-01', 'Shipped', 1200.00),
(2, 2, 2, '2025-01-03', 'Pending', 1700.00),
(3, 3, 1, '2025-01-05', 'Delivered', 300.00),
(4, 4, 4, '2025-01-07', 'Cancelled', 600.00),
(5, 5, 3, '2025-01-10', 'Shipped', 300.00);
